# Generated by Django 5.1.7 on 2025-12-05 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_servicerequest_assigned_to_alter_section_manager_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_initial', models.BooleanField(default=False, help_text='Is this a starting station?')),
                ('is_final', models.BooleanField(default=False, help_text='Is this a completion station?')),
                ('color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7, null=True)),
                ('order', models.IntegerField(default=0, help_text='Global display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicerequestlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Request Log', 'verbose_name_plural': 'Service Request Logs'},
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='station_entered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the request entered the current station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequestlog',
            name='log_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('station_change', 'Station Change'), ('assignment', 'Assignment Change'), ('update', 'General Update')], default='comment', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequestlog',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app1.servicerequest'),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sections', models.ManyToManyField(blank=True, help_text='Which sections can use this pipeline', to='app1.section')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pipeline',
            field=models.ForeignKey(default=1, help_text='Workflow pipeline for this request', on_delete=django.db.models.deletion.PROTECT, to='app1.pipeline'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PipelineStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Order of this station in the pipeline')),
                ('can_skip', models.BooleanField(default=False, help_text='Can this station be skipped?')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pipeline')),
                ('required_role', models.ForeignKey(blank=True, help_text='Required role to approve/move from this station', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.station')),
            ],
            options={
                'verbose_name': 'Pipeline Station',
                'verbose_name_plural': 'Pipeline Stations',
                'ordering': ['pipeline', 'order'],
                'unique_together': {('pipeline', 'order'), ('pipeline', 'station')},
            },
        ),
        migrations.AddField(
            model_name='pipeline',
            name='stations',
            field=models.ManyToManyField(related_name='pipelines', through='app1.PipelineStation', to='app1.station'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='current_station',
            field=models.ForeignKey(default=1, help_text='Current station in the workflow', on_delete=django.db.models.deletion.PROTECT, to='app1.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequestlog',
            name='from_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_from', to='app1.station'),
        ),
        migrations.AddField(
            model_name='servicerequestlog',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_to', to='app1.station'),
        ),
    ]
