# Generated by Django 5.1.7 on 2025-12-05 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_station_alter_servicerequestlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
