# Generated by Django 5.1.7 on 2025-12-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_station_allowed_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='current_station',
            field=models.ForeignKey(blank=True, help_text='Current station in the workflow', null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.station'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='Workflow pipeline for this request', null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.pipeline'),
        ),
        migrations.AlterField(
            model_name='station',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
