# Generated by Django 5.1.7 on 2025-12-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_servicerequest_current_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='workflow_type',
            field=models.CharField(choices=[('requires_materials', 'يتطلب إدخال المواد - Requires Materials Entry'), ('no_materials', 'يمكن الإكمال بدون مواد - Can Complete Without Materials'), ('requires_outsourcing', 'يتطلب خدمة خارجية - Requires Outsourced Service')], default='no_materials', help_text='Select the workflow type for this pipeline', max_length=50, verbose_name='نوع مسار العمل'),
        ),
    ]
