# Generated by Django 5.1.7 on 2025-12-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_pipeline_workflow_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='workflow_type',
        ),
    ]
