# Generated by Django 5.1.7 on 2025-12-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_pipeline_workflow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestation',
            name='can_create_completion_report',
            field=models.BooleanField(default=False, help_text='Can this station create a completion report?'),
        ),
        migrations.AddField(
            model_name='pipelinestation',
            name='can_create_inventory_order',
            field=models.BooleanField(default=False, help_text='Can this station create an inventory order?'),
        ),
        migrations.AddField(
            model_name='pipelinestation',
            name='can_create_purchase_order',
            field=models.BooleanField(default=False, help_text='Can this station create a purchase order?'),
        ),
    ]
