# Generated by Django 5.1.7 on 2025-12-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_pipelinestation_can_create_completion_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestation',
            name='can_send_back',
            field=models.BooleanField(default=False, help_text='Can this station send the request back to the previous station?'),
        ),
    ]
