# Generated by Django 5.1.7 on 2025-12-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_pipelinestation_can_send_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestation',
            name='can_edit_completion_report',
            field=models.BooleanField(default=False, help_text='Can this station edit the completion report?'),
        ),
        migrations.AddField(
            model_name='pipelinestation',
            name='can_edit_inventory_order',
            field=models.BooleanField(default=False, help_text='Can this station edit the inventory order?'),
        ),
        migrations.AddField(
            model_name='pipelinestation',
            name='can_edit_purchase_order',
            field=models.BooleanField(default=False, help_text='Can this station edit the purchase order?'),
        ),
    ]
