# Generated by Django 5.1.7 on 2025-12-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_pipelinestation_can_edit_completion_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestation',
            name='show_assigned_requests',
            field=models.BooleanField(default=False, help_text='Show assigned requests to this station?'),
        ),
    ]
