# Generated by Django 5.1.7 on 2025-12-06 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_pipelinestation_show_assigned_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinestation',
            name='required_role',
        ),
        migrations.RemoveField(
            model_name='station',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='pipelinestation',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users allowed to work on this station in this pipeline. Empty means all users can access.', to=settings.AUTH_USER_MODEL),
        ),
    ]
