# Generated by Django 5.1.7 on 2025-12-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_pipelinestation_required_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestation',
            name='show_the_managers_only',
            field=models.BooleanField(default=False, help_text='Show the managers only?'),
        ),
    ]
